#!/bin/bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp to the user's home directory on the server
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username"@"$server_ip":~/

# Check if the file transfer was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
