#!/usr/bin/env bash
# Sets up an Nginx server to redirect /redirect_me to another page with a "301 Moved Permanently" response.
# Additionally, includes a custom 404 page featuring the phrase "Ceci n'est pas une page".

# Updates available software packages by refreshing package lists.
apt-get update

# Installs the Nginx web server.
apt-get install -y nginx

# Creates the /etc/nginx/html directory to serve as Nginx's document root.
mkdir /etc/nginx/html

# Creates an empty index.html file within /etc/nginx/html.
touch /etc/nginx/html/index.html

# Sets the content of index.html to "Hello World!" using the echo command.
echo "Hello World!" > /etc/nginx/html/index.html

# Configures Nginx to listen on port 80 and serve files from /etc/nginx/html.
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Creates an empty 404.html file within /etc/nginx/html.
touch /etc/nginx/html/404.html

# Adds a "Ceci n'est pas une page" response to the 404.html file.
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Indicates completion of Nginx installation and configuration.
echo "Nginx installation and configuration completed."

# Generates a configuration file for the redirection.
echo "server {
    listen      80;
    listen      [::]:80;
    root        /etc/nginx/html;
    index       index.html index.htm;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }

}" | sudo tee /etc/nginx/sites-available/default

# Enables the new site configuration by creating a symbolic link.
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Tests the Nginx configuration and reloads the server.
sudo nginx -t
sudo service nginx reload
