#!/usr/bin/env bash
# Install HAproxy and it should have the following configurations
# Haproxy on lb-01 server
# Management via the init script
# Send traffic to web-01 and web-02 servers
# Requests using round-robin algorithm

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

sudo printf %s "global
    log 52.3.252.15 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 130907-web-01 54.237.46.237 check
    server 130907-web-02 100.26.120.223 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
